use teamwork;
ALTER TABLE `teamwork`.`QUESTION_BASIC` 
ADD COLUMN `TYPE` varchar(3) NOT NULL AFTER `SUBJECT_ID`,
ADD COLUMN `TIME_END_EXAM` varchar(16) NOT NULL AFTER `TIME_START_EXAM`;

ALTER TABLE `teamwork`.`QUESTION_DETAIL` 
ADD COLUMN `QUESTTION_DETAIL_CODE` int(3) NOT NULL AFTER `ID`,
DROP COLUMN `AWSER`;

use teamwork;
CREATE TABLE `teamwork`.`AWSER_DETAIL` (  
	`ID` varchar(20) NOT NULL,
    `QUESTION_DETAIL_ID` varchar(20) NOT NULL,
    `AWSER_DETAIL_CD_1` varchar(2) NOT NULL ,
	`AWSER_DETAIL_NAME_1` text(500) NOT NULL ,
    `AWSER_DETAIL_CD_2` varchar(2) NULL ,
	`AWSER_DETAIL_NAME_2` text(500) NULL ,
    `DEL_FLAG` Varchar(1) NOT NULL,
	`CREATE_USER` varchar(50)  NOT NULL,
	`CREATE_PROGRAM` varchar(50)  NOT NULL,
	`CREATE_DATE` Datetime NOT NULL,
	`UPDATE_USER` varchar(50)  NOT NULL,
	`UPDATE_PROGRAM` varchar(50)  NOT NULL,
	`UPDATE_DATE` Datetime NOT NULL,
    PRIMARY KEY (`ID`),
	CONSTRAINT `fk_awser_detail1` FOREIGN KEY (`QUESTION_DETAIL_ID`) REFERENCES `QUESTION_DETAIL` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
