use teamwork;
ALTER TABLE `teamwork`.`QUESTION_BASIC` 
ADD COLUMN `CONTENT` Text(500) NULL AFTER `SUBJECT_ID`,
ADD COLUMN `SCORE` varchar(3) NOT NULL AFTER `TIME_OVER_EXAM`;

ALTER TABLE `teamwork`.`history_exam` 
DROP COLUMN `QUESTION_RESULT`,
DROP COLUMN `ANSWER_RESULT`,
DROP COLUMN `QUESTION_DETAIL_ID`, RENAME TO  `teamwork`.`history_exam_basic` ;

CREATE TABLE `teamwork`.`HISTORY_EXAM_DETAIL` (  
	`ID` varchar(20) NOT NULL,
	`HISTORY_EXAM_BASIC_ID` varchar(20) NOT NULL ,
    `QUESTION_DETAIL_ID` varchar(20) NOT NULL ,
    `ANSWER_RESULT` varchar(50) NULL ,
    `QUESTION_RESULT` varchar(50) NOT NULL ,
    `DEL_FLAG` Varchar(1) NOT NULL,
	`CREATE_USER` varchar(50)  NOT NULL,
	`CREATE_PROGRAM` varchar(50)  NOT NULL,
	`CREATE_DATE` Datetime NOT NULL,
	`UPDATE_USER` varchar(50)  NOT NULL,
	`UPDATE_PROGRAM` varchar(50)  NOT NULL,
	`UPDATE_DATE` Datetime NOT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `fk_history_exam_detail1` FOREIGN KEY (`HISTORY_EXAM_BASIC_ID`) REFERENCES `HISTORY_EXAM_BASIC` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


use teamwork;
ALTER TABLE `teamwork`.`CATEGORY` 
ADD COLUMN `VALUE_EN` varchar(50) NOT NULL AFTER `VALUE`;

use teamwork;
ALTER TABLE `teamwork`.`SUBJECT` 
ADD COLUMN `NAME_EN` varchar(50) NOT NULL AFTER `NAME`;